//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTrees.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MonzoEntities : DbContext
    {
        public MonzoEntities()
            : base("name=MonzoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
    
        public virtual ObjectResult<SumOfEachCategory_Result> SumOfEachCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SumOfEachCategory_Result>("SumOfEachCategory");
        }
    
        public virtual ObjectResult<SumOfEachDay_Result> SumOfEachDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SumOfEachDay_Result>("SumOfEachDay");
        }
    }
}
